### PR TITLE
Handle GPP Base64 Quantum Quirks

### LINKED ISSUE #12: Header parsing does not work as expected
The first 2 strings from the [GPP string examples section](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md#gpp-string-examples) of the documentation give `error parsing GPP header` when I try to parse them using this library.

In the [GPP Consent String specification](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md), it says:

> Note that neither the header nor the recommended encoding mechanism for a discrete section utilizes base64 encoding but rather a modified version of it.

I think maybe that is the reason why.

### PR DESCRIPTION
**Pull request by SyntaxNode**
Fixes https://github.com/prebid/go-gpp/issues/12

### CODE REVIEW

File: parse_test.go [hunk 1]
```diff
@@ -20,7 +20,17 @@ type gppTestData struct {
 
 func TestParse(t *testing.T) {
 	testData := map[string]gppTestData{
-		"GPP-tcf": {
+		"gpp-tcf": {
+			description: "GPP string with EU TCF V2",
+			gppString:   "DBABM~CPXxRfAPXxRfAAfKABENB-CgAAAAAAAAAAYgAAAAAAAA",
```
Comment (SyntaxNode) [inline parse_test.go:25]: Updated examples to exactly match GPP docs. Somewhere along the way we added extra padding to those examples, which caused us to overlook this bug.

File: parse_test.go [hunk 2]
```diff
@@ -126,10 +136,10 @@ func TestParse(t *testing.T) {
 			},
 			expectedError: []error{fmt.Errorf("error parsing GPP header, section identifiers: error reading an int offset value in a Range(Fibonacci) entry(1): error reading bit 4 of Integer(Fibonacci): expected 1 bit at bit 32, but the byte array was only 4 bytes long")},
 		},
-		"GPP-uspca-error": {
+		"gpp-uspca-error": {
 			description:   "GPP string with USPCA",
 			gppString:     "DBABBgA~xlgWE",
-			expectedError: []error{fmt.Errorf("error parsing uspca consent string: illegal base64 data at input byte 4")},
+			expectedError: []error{fmt.Errorf("error parsing uspca consent string: unable to set field CoreSegment.SensitiveDataProcessing due to parse error: expected 2 bits to start at bit 32, but the byte array was only 4 bytes long")},
```
Comment (SyntaxNode) [inline parse_test.go:142]: It failed for the wrong reason before. Fixed expectation.

**Review by VeronikaSolovei9 — APPROVED** [review]

File: util/bitstream.go [hunk 3]
```diff
@@ -16,18 +16,30 @@ func NewBitStream(b []byte) *BitStream {
...
 
+// padLastQuantum pads the last quantum with zeros if it's incomplete to
+// ensure all bits are decoded using the standard base64 algorithm. The last
+// bits would otherwise be truncated down to the closest byte.
+func padLastQuantum(encoded string) string {
+	if (len(encoded) % 4) > 0 {
+		return encoded + "A" // pad with zeros
+	}
+
+	return encoded
```
Comment (VeronikaSolovei9) [inline util/bitstream.go:40]: Error occures only in case when remainder is 1. Do you think this optimization makes sense: 
```go
if (len(encoded) % 4) == 1 {...}
```

**Review by hhhjort — APPROVED** [review]
LGTM
